server:
  port: 8090
spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/microDB
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: PRODUCT-SERVICE

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#       defaultzone: http://localhost:8761/eureka
#  instance:
#   prefer-ip-address: true